// <auto-generated />
using System;
using MVCapplicacion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCapplicacion.Migrations
{
    [DbContext(typeof(MVCapplicacionContext))]
    [Migration("20190402171815_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCapplicacion.Models.Binnacle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Binnacle");
                });

            modelBuilder.Entity("MVCapplicacion.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BinnacleId");

                    b.Property<int>("ColorID");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BinnacleId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("MVCapplicacion.Models.Tag", b =>
                {
                    b.HasOne("MVCapplicacion.Models.Binnacle")
                        .WithMany("Tags")
                        .HasForeignKey("BinnacleId");
                });
#pragma warning restore 612, 618
        }
    }
}
